// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/asn1/v1/asn1.proto

package asn1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BitString struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Len                  uint32   `protobuf:"varint,2,opt,name=len,json=length,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitString) Reset()         { *m = BitString{} }
func (m *BitString) String() string { return proto.CompactTextString(m) }
func (*BitString) ProtoMessage()    {}
func (*BitString) Descriptor() ([]byte, []int) {
	return fileDescriptor_17256a470bdf4bb0, []int{0}
}

func (m *BitString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitString.Unmarshal(m, b)
}
func (m *BitString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitString.Marshal(b, m, deterministic)
}
func (m *BitString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitString.Merge(m, src)
}
func (m *BitString) XXX_Size() int {
	return xxx_messageInfo_BitString.Size(m)
}
func (m *BitString) XXX_DiscardUnknown() {
	xxx_messageInfo_BitString.DiscardUnknown(m)
}

var xxx_messageInfo_BitString proto.InternalMessageInfo

func (m *BitString) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *BitString) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func init() {
	proto.RegisterType((*BitString)(nil), "asn1.v1.BitString")
}

func init() {
	proto.RegisterFile("api/asn1/v1/asn1.proto", fileDescriptor_17256a470bdf4bb0)
}

var fileDescriptor_17256a470bdf4bb0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2c, 0xc8, 0xd4,
	0x4f, 0x2c, 0xce, 0x33, 0xd4, 0x2f, 0x33, 0x04, 0xd3, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42,
	0xec, 0x60, 0x76, 0x99, 0xa1, 0x92, 0x19, 0x17, 0xa7, 0x53, 0x66, 0x49, 0x70, 0x49, 0x51, 0x66,
	0x5e, 0xba, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x4b, 0x10, 0x84, 0x23, 0x24, 0xcc, 0xc5, 0x9c, 0x93, 0x9a, 0x27, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1,
	0x1b, 0xc4, 0x96, 0x93, 0x9a, 0x97, 0x5e, 0x92, 0xe1, 0x64, 0x1a, 0x65, 0x9c, 0x9e, 0x59, 0x92,
	0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x9f, 0x97, 0x5f, 0x5c, 0x50, 0x94, 0x9f, 0x95,
	0x9a, 0x5c, 0x02, 0x66, 0xeb, 0xe6, 0x64, 0x26, 0xe9, 0xa6, 0xe7, 0xeb, 0xa3, 0xdb, 0x9e, 0xc4,
	0x06, 0xb6, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xb4, 0x62, 0x03, 0x98, 0x00, 0x00,
	0x00,
}
