// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/logging/logging.proto

package logging

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ResponseStatus int32

const (
	ResponseStatus_OK                  ResponseStatus = 0
	ResponseStatus_FAILED              ResponseStatus = 1
	ResponseStatus_PRECONDITION_FAILED ResponseStatus = 2
)

var ResponseStatus_name = map[int32]string{
	0: "OK",
	1: "FAILED",
	2: "PRECONDITION_FAILED",
}

var ResponseStatus_value = map[string]int32{
	"OK":                  0,
	"FAILED":              1,
	"PRECONDITION_FAILED": 2,
}

func (x ResponseStatus) String() string {
	return proto.EnumName(ResponseStatus_name, int32(x))
}

func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{0}
}

// Logger level
type Level int32

const (
	// Debug log level
	Level_DEBUG Level = 0
	// Info log level
	Level_INFO Level = 1
	// Error log level
	Level_ERROR Level = 2
	// DPanic log level
	Level_DPANIC Level = 3
	// Panic log level
	Level_PANIC Level = 4
	// Fatal log level
	Level_FATAL Level = 5
)

var Level_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "ERROR",
	3: "DPANIC",
	4: "PANIC",
	5: "FATAL",
}

var Level_value = map[string]int32{
	"DEBUG":  0,
	"INFO":   1,
	"ERROR":  2,
	"DPANIC": 3,
	"PANIC":  4,
	"FATAL":  5,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}

func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{1}
}

// SetLevelRequest request for setting a logger level
type SetLevelRequest struct {
	// logger name
	LoggerName string `protobuf:"bytes,1,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	// logger level
	Level                Level    `protobuf:"varint,2,opt,name=level,proto3,enum=onos.lib.go.logging.Level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLevelRequest) Reset()         { *m = SetLevelRequest{} }
func (m *SetLevelRequest) String() string { return proto.CompactTextString(m) }
func (*SetLevelRequest) ProtoMessage()    {}
func (*SetLevelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{0}
}
func (m *SetLevelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLevelRequest.Unmarshal(m, b)
}
func (m *SetLevelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLevelRequest.Marshal(b, m, deterministic)
}
func (m *SetLevelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLevelRequest.Merge(m, src)
}
func (m *SetLevelRequest) XXX_Size() int {
	return xxx_messageInfo_SetLevelRequest.Size(m)
}
func (m *SetLevelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLevelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLevelRequest proto.InternalMessageInfo

func (m *SetLevelRequest) GetLoggerName() string {
	if m != nil {
		return m.LoggerName
	}
	return ""
}

func (m *SetLevelRequest) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_DEBUG
}

// SetLevelResponse response for setting a logger level
type SetLevelResponse struct {
	ResponseStatus       ResponseStatus `protobuf:"varint,1,opt,name=response_status,json=responseStatus,proto3,enum=onos.lib.go.logging.ResponseStatus" json:"response_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetLevelResponse) Reset()         { *m = SetLevelResponse{} }
func (m *SetLevelResponse) String() string { return proto.CompactTextString(m) }
func (*SetLevelResponse) ProtoMessage()    {}
func (*SetLevelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{1}
}
func (m *SetLevelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLevelResponse.Unmarshal(m, b)
}
func (m *SetLevelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLevelResponse.Marshal(b, m, deterministic)
}
func (m *SetLevelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLevelResponse.Merge(m, src)
}
func (m *SetLevelResponse) XXX_Size() int {
	return xxx_messageInfo_SetLevelResponse.Size(m)
}
func (m *SetLevelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLevelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetLevelResponse proto.InternalMessageInfo

func (m *SetLevelResponse) GetResponseStatus() ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return ResponseStatus_OK
}

// SetSinkRequest request for setting a sink
type SetSinkRequest struct {
	LoggerName           string   `protobuf:"bytes,1,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSinkRequest) Reset()         { *m = SetSinkRequest{} }
func (m *SetSinkRequest) String() string { return proto.CompactTextString(m) }
func (*SetSinkRequest) ProtoMessage()    {}
func (*SetSinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{2}
}
func (m *SetSinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSinkRequest.Unmarshal(m, b)
}
func (m *SetSinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSinkRequest.Marshal(b, m, deterministic)
}
func (m *SetSinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSinkRequest.Merge(m, src)
}
func (m *SetSinkRequest) XXX_Size() int {
	return xxx_messageInfo_SetSinkRequest.Size(m)
}
func (m *SetSinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSinkRequest proto.InternalMessageInfo

func (m *SetSinkRequest) GetLoggerName() string {
	if m != nil {
		return m.LoggerName
	}
	return ""
}

func (m *SetSinkRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SetSinkRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// SetSinkResponse response for setting a sink
type SetSinkResponse struct {
	ResponseStatus       ResponseStatus `protobuf:"varint,1,opt,name=response_status,json=responseStatus,proto3,enum=onos.lib.go.logging.ResponseStatus" json:"response_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetSinkResponse) Reset()         { *m = SetSinkResponse{} }
func (m *SetSinkResponse) String() string { return proto.CompactTextString(m) }
func (*SetSinkResponse) ProtoMessage()    {}
func (*SetSinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{3}
}
func (m *SetSinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSinkResponse.Unmarshal(m, b)
}
func (m *SetSinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSinkResponse.Marshal(b, m, deterministic)
}
func (m *SetSinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSinkResponse.Merge(m, src)
}
func (m *SetSinkResponse) XXX_Size() int {
	return xxx_messageInfo_SetSinkResponse.Size(m)
}
func (m *SetSinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetSinkResponse proto.InternalMessageInfo

func (m *SetSinkResponse) GetResponseStatus() ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return ResponseStatus_OK
}

func init() {
	proto.RegisterEnum("onos.lib.go.logging.ResponseStatus", ResponseStatus_name, ResponseStatus_value)
	proto.RegisterEnum("onos.lib.go.logging.Level", Level_name, Level_value)
	proto.RegisterType((*SetLevelRequest)(nil), "onos.lib.go.logging.SetLevelRequest")
	proto.RegisterType((*SetLevelResponse)(nil), "onos.lib.go.logging.SetLevelResponse")
	proto.RegisterType((*SetSinkRequest)(nil), "onos.lib.go.logging.SetSinkRequest")
	proto.RegisterType((*SetSinkResponse)(nil), "onos.lib.go.logging.SetSinkResponse")
}

func init() { proto.RegisterFile("api/logging/logging.proto", fileDescriptor_282a7fd5e5377550) }

var fileDescriptor_282a7fd5e5377550 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x5d, 0x6f, 0xa2, 0x40,
	0x14, 0x15, 0x14, 0x56, 0xef, 0x26, 0x38, 0x19, 0x37, 0x59, 0xd7, 0x97, 0x35, 0xe8, 0x26, 0xc6,
	0x07, 0x76, 0xe3, 0x3e, 0xf7, 0x81, 0x0a, 0x36, 0xa4, 0x04, 0xcc, 0x60, 0xd3, 0xf4, 0x89, 0x62,
	0x3b, 0x21, 0x44, 0x64, 0x28, 0x60, 0x93, 0xfe, 0xb2, 0xfe, 0xbd, 0x06, 0x06, 0xd3, 0xda, 0xd8,
	0x8f, 0x97, 0x3e, 0x71, 0xe6, 0xdc, 0x73, 0xcf, 0x70, 0xcf, 0x5c, 0xf8, 0x15, 0xa4, 0xd1, 0xdf,
	0x98, 0x85, 0x61, 0x94, 0x84, 0xfb, 0xaf, 0x96, 0x66, 0xac, 0x60, 0xb8, 0xc7, 0x12, 0x96, 0x6b,
	0x71, 0xb4, 0xd6, 0x42, 0xa6, 0xd5, 0x25, 0xf5, 0x16, 0xba, 0x1e, 0x2d, 0x6c, 0x7a, 0x4f, 0x63,
	0x42, 0xef, 0x76, 0x34, 0x2f, 0xf0, 0x6f, 0xf8, 0x5e, 0x56, 0x69, 0xe6, 0x27, 0xc1, 0x96, 0xf6,
	0x85, 0xa1, 0x30, 0xe9, 0x10, 0xe0, 0x94, 0x13, 0x6c, 0x29, 0xfe, 0x07, 0x52, 0x5c, 0x36, 0xf4,
	0xc5, 0xa1, 0x30, 0x51, 0x66, 0x03, 0xed, 0x88, 0xb1, 0xc6, 0x2d, 0xb9, 0x50, 0xbd, 0x06, 0xf4,
	0x7c, 0x4b, 0x9e, 0xb2, 0x24, 0xa7, 0xd8, 0x86, 0x6e, 0x56, 0x63, 0x3f, 0x2f, 0x82, 0x62, 0x97,
	0x57, 0x57, 0x29, 0xb3, 0xd1, 0x51, 0xbf, 0x7d, 0x9f, 0x57, 0x49, 0x89, 0x92, 0x1d, 0x9c, 0xd5,
	0x2b, 0x50, 0x3c, 0x5a, 0x78, 0x51, 0xb2, 0xf9, 0xf4, 0x18, 0x3f, 0x40, 0x2a, 0x58, 0x1a, 0xdd,
	0x54, 0x63, 0x74, 0x08, 0x3f, 0x60, 0x04, 0xcd, 0x0d, 0x7d, 0xe8, 0x37, 0x2b, 0xae, 0x84, 0xaa,
	0x5f, 0x45, 0xc4, 0xad, 0xbf, 0xe2, 0xdf, 0xa7, 0x27, 0xa0, 0x1c, 0x2a, 0xb0, 0x0c, 0xa2, 0x7b,
	0x8e, 0x1a, 0x18, 0x40, 0x5e, 0xe8, 0x96, 0x6d, 0x1a, 0x48, 0xc0, 0x3f, 0xa1, 0xb7, 0x24, 0xe6,
	0xdc, 0x75, 0x0c, 0x6b, 0x65, 0xb9, 0x8e, 0x5f, 0x17, 0xc4, 0xa9, 0x05, 0x52, 0x95, 0x2c, 0xee,
	0x80, 0x64, 0x98, 0xa7, 0x17, 0x67, 0xa8, 0x81, 0xdb, 0xd0, 0xb2, 0x9c, 0x85, 0x8b, 0x84, 0x92,
	0x34, 0x09, 0x71, 0x09, 0x12, 0x4b, 0x37, 0x63, 0xa9, 0x3b, 0xd6, 0x1c, 0x35, 0x4b, 0x9a, 0xc3,
	0x56, 0x09, 0x17, 0xfa, 0x4a, 0xb7, 0x91, 0x34, 0x7b, 0x14, 0x40, 0xe6, 0x09, 0xe1, 0x4b, 0x68,
	0xef, 0x9f, 0x0c, 0x8f, 0x8f, 0x4e, 0xf5, 0x6a, 0x6f, 0x06, 0x7f, 0x3e, 0x50, 0xd5, 0xd9, 0xad,
	0xe0, 0x5b, 0x1d, 0x27, 0x1e, 0xbd, 0xd5, 0xf1, 0xe2, 0x1d, 0x07, 0xe3, 0xf7, 0x45, 0xdc, 0x75,
	0x2d, 0x57, 0x3b, 0xfe, 0xff, 0x29, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x02, 0xeb, 0xd4, 0x00, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	// Sets a logger level
	SetLevel(ctx context.Context, in *SetLevelRequest, opts ...grpc.CallOption) (*SetLevelResponse, error)
	// Sets a sink for a logger
	SetSink(ctx context.Context, in *SetSinkRequest, opts ...grpc.CallOption) (*SetSinkResponse, error)
}

type loggerClient struct {
	cc *grpc.ClientConn
}

func NewLoggerClient(cc *grpc.ClientConn) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) SetLevel(ctx context.Context, in *SetLevelRequest, opts ...grpc.CallOption) (*SetLevelResponse, error) {
	out := new(SetLevelResponse)
	err := c.cc.Invoke(ctx, "/onos.lib.go.logging.logger/SetLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) SetSink(ctx context.Context, in *SetSinkRequest, opts ...grpc.CallOption) (*SetSinkResponse, error) {
	out := new(SetSinkResponse)
	err := c.cc.Invoke(ctx, "/onos.lib.go.logging.logger/SetSink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	// Sets a logger level
	SetLevel(context.Context, *SetLevelRequest) (*SetLevelResponse, error)
	// Sets a sink for a logger
	SetSink(context.Context, *SetSinkRequest) (*SetSinkResponse, error)
}

// UnimplementedLoggerServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServer struct {
}

func (*UnimplementedLoggerServer) SetLevel(ctx context.Context, req *SetLevelRequest) (*SetLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLevel not implemented")
}
func (*UnimplementedLoggerServer) SetSink(ctx context.Context, req *SetSinkRequest) (*SetSinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSink not implemented")
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_SetLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).SetLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.lib.go.logging.logger/SetLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).SetLevel(ctx, req.(*SetLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_SetSink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).SetSink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.lib.go.logging.logger/SetSink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).SetSink(ctx, req.(*SetSinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onos.lib.go.logging.logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLevel",
			Handler:    _Logger_SetLevel_Handler,
		},
		{
			MethodName: "SetSink",
			Handler:    _Logger_SetSink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/logging/logging.proto",
}
