// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/logging/logging.proto

package logging

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ResponseStatus int32

const (
	ResponseStatus_OK                  ResponseStatus = 0
	ResponseStatus_FAILED              ResponseStatus = 1
	ResponseStatus_PRECONDITION_FAILED ResponseStatus = 2
)

var ResponseStatus_name = map[int32]string{
	0: "OK",
	1: "FAILED",
	2: "PRECONDITION_FAILED",
}

var ResponseStatus_value = map[string]int32{
	"OK":                  0,
	"FAILED":              1,
	"PRECONDITION_FAILED": 2,
}

func (x ResponseStatus) String() string {
	return proto.EnumName(ResponseStatus_name, int32(x))
}

func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{0}
}

// Logger level
type Level int32

const (
	// Debug log level
	Level_DEBUG Level = 0
	// Info log level
	Level_INFO Level = 1
	// Warn log level
	Level_WARN Level = 2
	// Error log level
	Level_ERROR Level = 3
	// DPanic log level
	Level_DPANIC Level = 4
	// Panic log level
	Level_PANIC Level = 5
	// Fatal log level
	Level_FATAL Level = 6
)

var Level_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "WARN",
	3: "ERROR",
	4: "DPANIC",
	5: "PANIC",
	6: "FATAL",
}

var Level_value = map[string]int32{
	"DEBUG":  0,
	"INFO":   1,
	"WARN":   2,
	"ERROR":  3,
	"DPANIC": 4,
	"PANIC":  5,
	"FATAL":  6,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}

func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{1}
}

// SetLevelRequest request for setting a logger level
type SetLevelRequest struct {
	// logger name
	LoggerName string `protobuf:"bytes,1,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	// logger level
	Level                Level    `protobuf:"varint,2,opt,name=level,proto3,enum=onos.lib.go.logging.Level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLevelRequest) Reset()         { *m = SetLevelRequest{} }
func (m *SetLevelRequest) String() string { return proto.CompactTextString(m) }
func (*SetLevelRequest) ProtoMessage()    {}
func (*SetLevelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{0}
}
func (m *SetLevelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLevelRequest.Unmarshal(m, b)
}
func (m *SetLevelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLevelRequest.Marshal(b, m, deterministic)
}
func (m *SetLevelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLevelRequest.Merge(m, src)
}
func (m *SetLevelRequest) XXX_Size() int {
	return xxx_messageInfo_SetLevelRequest.Size(m)
}
func (m *SetLevelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLevelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLevelRequest proto.InternalMessageInfo

func (m *SetLevelRequest) GetLoggerName() string {
	if m != nil {
		return m.LoggerName
	}
	return ""
}

func (m *SetLevelRequest) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_DEBUG
}

// SetLevelResponse response for setting a logger level
type SetLevelResponse struct {
	ResponseStatus       ResponseStatus `protobuf:"varint,1,opt,name=response_status,json=responseStatus,proto3,enum=onos.lib.go.logging.ResponseStatus" json:"response_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetLevelResponse) Reset()         { *m = SetLevelResponse{} }
func (m *SetLevelResponse) String() string { return proto.CompactTextString(m) }
func (*SetLevelResponse) ProtoMessage()    {}
func (*SetLevelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{1}
}
func (m *SetLevelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLevelResponse.Unmarshal(m, b)
}
func (m *SetLevelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLevelResponse.Marshal(b, m, deterministic)
}
func (m *SetLevelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLevelResponse.Merge(m, src)
}
func (m *SetLevelResponse) XXX_Size() int {
	return xxx_messageInfo_SetLevelResponse.Size(m)
}
func (m *SetLevelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLevelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetLevelResponse proto.InternalMessageInfo

func (m *SetLevelResponse) GetResponseStatus() ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return ResponseStatus_OK
}

// SetDebugModeRequest enable/disable debug mode of the logger
type SetDebugModeRequest struct {
	Debug                bool     `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDebugModeRequest) Reset()         { *m = SetDebugModeRequest{} }
func (m *SetDebugModeRequest) String() string { return proto.CompactTextString(m) }
func (*SetDebugModeRequest) ProtoMessage()    {}
func (*SetDebugModeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{2}
}
func (m *SetDebugModeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDebugModeRequest.Unmarshal(m, b)
}
func (m *SetDebugModeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDebugModeRequest.Marshal(b, m, deterministic)
}
func (m *SetDebugModeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDebugModeRequest.Merge(m, src)
}
func (m *SetDebugModeRequest) XXX_Size() int {
	return xxx_messageInfo_SetDebugModeRequest.Size(m)
}
func (m *SetDebugModeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDebugModeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDebugModeRequest proto.InternalMessageInfo

func (m *SetDebugModeRequest) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

// SetDebugModeResponse response for setting debug mode of a logger
type SetDebugModeResponse struct {
	ResponseStatus       ResponseStatus `protobuf:"varint,1,opt,name=response_status,json=responseStatus,proto3,enum=onos.lib.go.logging.ResponseStatus" json:"response_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetDebugModeResponse) Reset()         { *m = SetDebugModeResponse{} }
func (m *SetDebugModeResponse) String() string { return proto.CompactTextString(m) }
func (*SetDebugModeResponse) ProtoMessage()    {}
func (*SetDebugModeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_282a7fd5e5377550, []int{3}
}
func (m *SetDebugModeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDebugModeResponse.Unmarshal(m, b)
}
func (m *SetDebugModeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDebugModeResponse.Marshal(b, m, deterministic)
}
func (m *SetDebugModeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDebugModeResponse.Merge(m, src)
}
func (m *SetDebugModeResponse) XXX_Size() int {
	return xxx_messageInfo_SetDebugModeResponse.Size(m)
}
func (m *SetDebugModeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDebugModeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDebugModeResponse proto.InternalMessageInfo

func (m *SetDebugModeResponse) GetResponseStatus() ResponseStatus {
	if m != nil {
		return m.ResponseStatus
	}
	return ResponseStatus_OK
}

func init() {
	proto.RegisterEnum("onos.lib.go.logging.ResponseStatus", ResponseStatus_name, ResponseStatus_value)
	proto.RegisterEnum("onos.lib.go.logging.Level", Level_name, Level_value)
	proto.RegisterType((*SetLevelRequest)(nil), "onos.lib.go.logging.SetLevelRequest")
	proto.RegisterType((*SetLevelResponse)(nil), "onos.lib.go.logging.SetLevelResponse")
	proto.RegisterType((*SetDebugModeRequest)(nil), "onos.lib.go.logging.SetDebugModeRequest")
	proto.RegisterType((*SetDebugModeResponse)(nil), "onos.lib.go.logging.SetDebugModeResponse")
}

func init() { proto.RegisterFile("api/logging/logging.proto", fileDescriptor_282a7fd5e5377550) }

var fileDescriptor_282a7fd5e5377550 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xc1, 0x6a, 0xc2, 0x40,
	0x10, 0x35, 0xa9, 0x09, 0x3a, 0x85, 0xb8, 0xac, 0x42, 0xad, 0x97, 0x4a, 0xda, 0x82, 0x58, 0x48,
	0x8b, 0x3d, 0xf7, 0x90, 0x9a, 0x58, 0x42, 0xd3, 0x44, 0x36, 0x16, 0x8f, 0x36, 0x92, 0x25, 0x08,
	0x31, 0x6b, 0x93, 0xb5, 0xdf, 0x5f, 0x36, 0x6b, 0x28, 0x16, 0xa1, 0xa7, 0x9e, 0xf2, 0x66, 0xde,
	0x9b, 0x37, 0x99, 0x9d, 0x81, 0xcb, 0x78, 0xb7, 0xb9, 0xcf, 0x58, 0x9a, 0x6e, 0xf2, 0xb4, 0xfe,
	0x5a, 0xbb, 0x82, 0x71, 0x86, 0xbb, 0x2c, 0x67, 0xa5, 0x95, 0x6d, 0xd6, 0x56, 0xca, 0xac, 0x03,
	0x65, 0x26, 0xd0, 0x89, 0x28, 0xf7, 0xe9, 0x17, 0xcd, 0x08, 0xfd, 0xdc, 0xd3, 0x92, 0xe3, 0x2b,
	0x38, 0x17, 0x2c, 0x2d, 0x56, 0x79, 0xbc, 0xa5, 0x7d, 0x65, 0xa8, 0x8c, 0xda, 0x04, 0x64, 0x2a,
	0x88, 0xb7, 0x14, 0x3f, 0x80, 0x96, 0x89, 0x82, 0xbe, 0x3a, 0x54, 0x46, 0xc6, 0x64, 0x60, 0x9d,
	0x30, 0xb6, 0xa4, 0xa5, 0x14, 0x9a, 0x1f, 0x80, 0x7e, 0xba, 0x94, 0x3b, 0x96, 0x97, 0x14, 0xfb,
	0xd0, 0x29, 0x0e, 0x78, 0x55, 0xf2, 0x98, 0xef, 0xcb, 0xaa, 0x95, 0x31, 0xb9, 0x3e, 0xe9, 0x57,
	0xd7, 0x45, 0x95, 0x94, 0x18, 0xc5, 0x51, 0x6c, 0xde, 0x41, 0x37, 0xa2, 0xdc, 0xa1, 0xeb, 0x7d,
	0xfa, 0xc6, 0x12, 0x5a, 0xcf, 0xd2, 0x03, 0x2d, 0x11, 0xb9, 0xca, 0xba, 0x45, 0x64, 0x60, 0x26,
	0xd0, 0x3b, 0x16, 0xff, 0xc7, 0x2f, 0x8d, 0x9f, 0xc0, 0x38, 0x56, 0x60, 0x1d, 0xd4, 0xf0, 0x15,
	0x35, 0x30, 0x80, 0x3e, 0xb3, 0x3d, 0xdf, 0x75, 0x90, 0x82, 0x2f, 0xa0, 0x3b, 0x27, 0xee, 0x34,
	0x0c, 0x1c, 0x6f, 0xe1, 0x85, 0xc1, 0xea, 0x40, 0xa8, 0xe3, 0x08, 0xb4, 0xea, 0xc1, 0x70, 0x1b,
	0x34, 0xc7, 0x7d, 0x7e, 0x7f, 0x41, 0x0d, 0xdc, 0x82, 0xa6, 0x17, 0xcc, 0x42, 0xa4, 0x08, 0xb4,
	0xb4, 0x49, 0x80, 0x54, 0x41, 0xbb, 0x84, 0x84, 0x04, 0x9d, 0x09, 0x5f, 0x67, 0x6e, 0x07, 0xde,
	0x14, 0x35, 0x45, 0x5a, 0x42, 0x4d, 0xc0, 0x99, 0xbd, 0xb0, 0x7d, 0xa4, 0x4f, 0x62, 0xd0, 0xe5,
	0x22, 0xf1, 0x12, 0x5a, 0xf5, 0x4a, 0xf0, 0xcd, 0xc9, 0xf1, 0x7e, 0xdd, 0xc5, 0xe0, 0xf6, 0x0f,
	0x95, 0x1c, 0x75, 0xad, 0x57, 0xd7, 0xf6, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x56, 0x18,
	0x52, 0x8a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	// Sets a logger level
	SetLevel(ctx context.Context, in *SetLevelRequest, opts ...grpc.CallOption) (*SetLevelResponse, error)
}

type loggerClient struct {
	cc *grpc.ClientConn
}

func NewLoggerClient(cc *grpc.ClientConn) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) SetLevel(ctx context.Context, in *SetLevelRequest, opts ...grpc.CallOption) (*SetLevelResponse, error) {
	out := new(SetLevelResponse)
	err := c.cc.Invoke(ctx, "/onos.lib.go.logging.logger/SetLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	// Sets a logger level
	SetLevel(context.Context, *SetLevelRequest) (*SetLevelResponse, error)
}

// UnimplementedLoggerServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServer struct {
}

func (*UnimplementedLoggerServer) SetLevel(ctx context.Context, req *SetLevelRequest) (*SetLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLevel not implemented")
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_SetLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).SetLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.lib.go.logging.logger/SetLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).SetLevel(ctx, req.(*SetLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onos.lib.go.logging.logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLevel",
			Handler:    _Logger_SetLevel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/logging/logging.proto",
}
