// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/rbac/rbac.proto

package rbac

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Metadata struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f53967f4a28029a, []int{0}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Role
type Role struct {
	Metadata             *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Rules                []*Rule   `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f53967f4a28029a, []int{1}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Role) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

// Rule
type Rule struct {
	Groups               []string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Services             []string `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	Verbs                []string `protobuf:"bytes,3,rep,name=verbs,proto3" json:"verbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f53967f4a28029a, []int{2}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Rule) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Rule) GetVerbs() []string {
	if m != nil {
		return m.Verbs
	}
	return nil
}

func init() {
	proto.RegisterType((*Metadata)(nil), "onos.lib.go.rbac.Metadata")
	proto.RegisterType((*Role)(nil), "onos.lib.go.rbac.Role")
	proto.RegisterType((*Rule)(nil), "onos.lib.go.rbac.Rule")
}

func init() { proto.RegisterFile("api/rbac/rbac.proto", fileDescriptor_9f53967f4a28029a) }

var fileDescriptor_9f53967f4a28029a = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xd1, 0x4a, 0x87, 0x30,
	0x14, 0xc6, 0x31, 0xfd, 0x8b, 0x1e, 0x09, 0xe2, 0x14, 0x32, 0xbc, 0x08, 0xf1, 0xca, 0x8b, 0x58,
	0x60, 0xd0, 0x5b, 0x04, 0xb1, 0x9e, 0x60, 0xb3, 0x83, 0x08, 0xd3, 0xc9, 0xa6, 0x3e, 0x7f, 0xb8,
	0x99, 0x17, 0x75, 0x33, 0xf6, 0xdb, 0xf7, 0xdb, 0xb7, 0x71, 0xe0, 0x51, 0x2e, 0xe3, 0xab, 0x55,
	0xb2, 0xf7, 0x0b, 0x5f, 0xac, 0x59, 0x0d, 0x3e, 0x98, 0xd9, 0x38, 0xae, 0x47, 0xc5, 0x07, 0xc3,
	0x8f, 0xf3, 0xe6, 0x19, 0xb2, 0x0f, 0x5a, 0xe5, 0xb7, 0x5c, 0x25, 0x22, 0x24, 0xb3, 0x9c, 0x88,
	0x45, 0x75, 0xd4, 0xe6, 0xc2, 0xef, 0x1b, 0x0d, 0x89, 0x30, 0x9a, 0xf0, 0x1d, 0xb2, 0xe9, 0xf4,
	0x7c, 0x5e, 0x74, 0x15, 0xff, 0x5b, 0xc6, 0x7f, 0x9b, 0xc4, 0xe5, 0xe2, 0x0b, 0xdc, 0xec, 0xa6,
	0xc9, 0xb1, 0xb8, 0x8e, 0xdb, 0xa2, 0x2b, 0xff, 0x5f, 0x12, 0x9b, 0x26, 0x11, 0xa4, 0xe6, 0x13,
	0x92, 0x03, 0xb1, 0x84, 0x74, 0xb0, 0x66, 0x5b, 0x1c, 0x8b, 0xea, 0xb8, 0xcd, 0xc5, 0x49, 0x58,
	0x41, 0xe6, 0xc8, 0xee, 0x63, 0x4f, 0x8e, 0xdd, 0xf9, 0xe4, 0x62, 0x7c, 0x82, 0xdb, 0x4e, 0x56,
	0x85, 0x97, 0x72, 0x11, 0xa0, 0xbb, 0x87, 0xe2, 0xf8, 0xff, 0x57, 0xb0, 0x54, 0xea, 0xe7, 0xf0,
	0xf6, 0x13, 0x00, 0x00, 0xff, 0xff, 0x15, 0xa0, 0x96, 0xc0, 0x1e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoleServiceClient is the client API for RoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoleServiceClient interface {
}

type roleServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoleServiceClient(cc *grpc.ClientConn) RoleServiceClient {
	return &roleServiceClient{cc}
}

// RoleServiceServer is the server API for RoleService service.
type RoleServiceServer interface {
}

// UnimplementedRoleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRoleServiceServer struct {
}

func RegisterRoleServiceServer(s *grpc.Server, srv RoleServiceServer) {
	s.RegisterService(&_RoleService_serviceDesc, srv)
}

var _RoleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onos.lib.go.rbac.RoleService",
	HandlerType: (*RoleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/rbac/rbac.proto",
}
