// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/rbac/rbac.proto

package rbac

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Role
type Role struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Groups               []string `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	Rules                []*Rule  `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f53967f4a28029a, []int{0}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Role) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

// Rule
type Rule struct {
	Services             []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Verbs                []string `protobuf:"bytes,2,rep,name=verbs,proto3" json:"verbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f53967f4a28029a, []int{1}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Rule) GetVerbs() []string {
	if m != nil {
		return m.Verbs
	}
	return nil
}

func init() {
	proto.RegisterType((*Role)(nil), "onos.lib.go.rbac.Role")
	proto.RegisterType((*Rule)(nil), "onos.lib.go.rbac.Rule")
}

func init() { proto.RegisterFile("api/rbac/rbac.proto", fileDescriptor_9f53967f4a28029a) }

var fileDescriptor_9f53967f4a28029a = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xce, 0xc1, 0xca, 0x83, 0x30,
	0x0c, 0x07, 0x70, 0xfc, 0xac, 0xf2, 0x99, 0x5d, 0x46, 0x36, 0xa4, 0xec, 0x24, 0x9e, 0x3c, 0x8c,
	0x0e, 0xdc, 0x65, 0xcf, 0xd1, 0x27, 0x58, 0x2b, 0x41, 0x84, 0xce, 0x48, 0x3b, 0x7d, 0xfe, 0x61,
	0xdd, 0x76, 0xd8, 0x25, 0xe4, 0x17, 0xc2, 0x3f, 0x81, 0x83, 0x99, 0x86, 0x8b, 0xb7, 0xa6, 0x8b,
	0x45, 0x4d, 0x9e, 0x9f, 0x8c, 0x7b, 0x1e, 0x39, 0x28, 0x37, 0x58, 0xd5, 0xb3, 0x5a, 0xe7, 0xf5,
	0x1d, 0x84, 0x66, 0x47, 0x88, 0x20, 0x46, 0xf3, 0x20, 0x99, 0x54, 0x49, 0x53, 0xe8, 0xd8, 0x63,
	0x09, 0x79, 0xef, 0x79, 0x9e, 0x82, 0xfc, 0xab, 0xd2, 0xa6, 0xd0, 0x6f, 0xe1, 0x19, 0x32, 0x3f,
	0x3b, 0x0a, 0x32, 0xad, 0xd2, 0x66, 0xd7, 0x96, 0xea, 0x37, 0x55, 0xe9, 0xd9, 0x91, 0xde, 0x96,
	0xea, 0x1b, 0x88, 0x95, 0x78, 0x82, 0xff, 0x40, 0x7e, 0x19, 0x3a, 0x0a, 0x32, 0x89, 0x79, 0x5f,
	0xe3, 0x11, 0xb2, 0x85, 0xbc, 0xfd, 0x1c, 0xda, 0xd0, 0xe6, 0x20, 0xb4, 0x35, 0x9d, 0xcd, 0xe3,
	0xf3, 0xd7, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x64, 0x16, 0x55, 0xd3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RbacClient is the client API for Rbac service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RbacClient interface {
}

type rbacClient struct {
	cc *grpc.ClientConn
}

func NewRbacClient(cc *grpc.ClientConn) RbacClient {
	return &rbacClient{cc}
}

// RbacServer is the server API for Rbac service.
type RbacServer interface {
}

// UnimplementedRbacServer can be embedded to have forward compatible implementations.
type UnimplementedRbacServer struct {
}

func RegisterRbacServer(s *grpc.Server, srv RbacServer) {
	s.RegisterService(&_Rbac_serviceDesc, srv)
}

var _Rbac_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onos.lib.go.rbac.Rbac",
	HandlerType: (*RbacServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/rbac/rbac.proto",
}
